[package]
name = "autismarchia-back"
version = "0.1.0"
authors = ["pwlodarczyk92 <pwlodarczyk92@gmail.com>"]

[lib]
name = "autismarchia_back"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rand = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
ordered-float = "0.5"
